#!/usr/bin/env python3
"""
generate_skill_pr.py
Generates a standardized Markdown Pull Request description for publishing 
a skill to the shared repository.
"""

import sys
import argparse
from pathlib import Path

# ── ANSI Terminal Styling ─────────────────────────────────────────────────────

COLOR_GREEN = "\033[92m"
COLOR_RED = "\033[91m"
COLOR_YELLOW = "\033[93m"
COLOR_CYAN = "\033[96m"
COLOR_BOLD = "\033[1m"
COLOR_RESET = "\033[0m"

def supports_color() -> bool:
    import os
    if os.name == "nt":
        return True
    return sys.stdout.isatty()

def style(text: str, color_code: str) -> str:
    if supports_color():
        return f"{color_code}{text}{COLOR_RESET}"
    return text

PR_TEMPLATE = """# Skill Publication / Update Request: `{skill_name}`

## 📝 Overview
**Version:** `v{version}`
**Owner:** `{owner}`
**Tier:** `{tier}`

{description}

## 🛡️ Governance Checklist
Please confirm the following checks have been completed before requesting review:

- [ ] **Policy Enforcer:** Passed `skill-governance-policy` audit.
- [ ] **Health Check:** Passed `skill-health-checker` with Grade B or higher.
- [ ] **Dry-Run Tested:** Simulated via `dry-run-skill-tester` to ensure safety.
- [ ] **Secrets Scanned:** Passed `secret-leak-guard` (no hardcoded credentials).
- [ ] **Changelog:** Updated `.versions/CHANGELOG.md`.

## ⚙️ Impact Radius
*(Describe what systems, files, or workflows this skill interacts with. E.g., "Modifies Kubernetes deployments", "Creates local files only")*

> Write impact radius here...

## 🔄 Replaces / Deprecates
*(Does this replace an older skill? If yes, list it here and ensure the old skill has `deprecated: true` in its frontmatter)*
- None

---
*Auto-generated by `skill-governance-policy` agent.*
"""

def extract_metadata(skill_md_path: Path) -> dict:
    import re
    meta = {"name": "Unknown", "version": "Unknown", "owner": "Unknown", "tier": "Unknown", "description": ""}
    if not skill_md_path.exists():
        return meta
        
    content = skill_md_path.read_text(errors="ignore")
    in_fm = False
    desc_lines = []
    in_desc = False
    
    for line in content.splitlines():
        if line.strip() == "---":
            in_fm = not in_fm
            if not in_fm:
                break
            continue
            
        if in_fm:
            m = re.match(r"^([a-zA-Z0-9_-]+):\s*(.*)", line)
            if m:
                key = m.group(1)
                val = m.group(2).strip(" '\"")
                if key == "description":
                    in_desc = True
                    if val and val != "|":
                        desc_lines.append(val)
                else:
                    in_desc = False
                    if key in meta:
                        meta[key] = val
            elif in_desc and (line.startswith("  ") or line.startswith("\t")):
                desc_lines.append(line.strip())
                
    meta["description"] = " ".join(desc_lines)
    return meta

def main():
    parser = argparse.ArgumentParser(description="Generate PR Template for Skill")
    parser.add_argument("--skill-dir", required=True, help="Path to the skill directory")
    parser.add_argument("--pr-type", choices=["NEW_SKILL", "UPDATE", "DEPRECATION"], default="NEW_SKILL")
    args = parser.parse_args()

    skill_dir = Path(args.skill_dir)
    skill_md = skill_dir / "SKILL.md"
    
    if not skill_md.exists():
        print(style(f"Error: {skill_md} not found.", COLOR_RED), file=sys.stderr)
        sys.exit(2)
        
    meta = extract_metadata(skill_md)
    
    template = PR_TEMPLATE.format(
        skill_name=meta["name"],
        version=meta["version"],
        owner=meta["owner"],
        tier=meta["tier"],
        description=f"**Purpose:** {meta['description']}"
    )
    
    print("\n" + style("=" * 60, COLOR_CYAN))
    print(style("📋 GENERATED PULL REQUEST TEMPLATE", COLOR_BOLD + COLOR_GREEN))
    print(style("=" * 60, COLOR_CYAN) + "\n")
    print(template)
    print("\n" + style("=" * 60, COLOR_CYAN))
    print(style("Action: Copy the text above into your GitHub/GitLab Pull Request.", COLOR_YELLOW))

if __name__ == "__main__":
    main()
