version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      production-framework:
        dependency-patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@prisma/*"
          - "prisma"
      tooling-dev:
        dependency-types:
          - "development"
