FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Копируем standalone билд и статические файлы
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public

# Копируем сгенерированный Prisma клиент для Linux
COPY node_modules/.prisma ./node_modules/.prisma
COPY node_modules/@prisma ./node_modules/@prisma

EXPOSE 3000

CMD ["node", "server.js"]
