import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'node',
    globals: true,
    testTimeout: 15000,
    setupFiles: [],
    alias: {
      '@': path.resolve(__dirname, './src')
    },
    include: [
      'src/__tests__/financial/financial-security-audit.test.ts',
      'src/__tests__/catalog-pagination-offset.test.ts',
      'src/__tests__/admin-switchers-security.test.ts',
      'src/__tests__/ai-draft-caching-speed.test.ts',
      'src/__tests__/orders-clients-pagination.test.ts',
      'src/__tests__/dark-mode-audit.test.ts',
      'src/__tests__/maintenance-screens.test.ts',
      'src/__tests__/table-density.test.ts',
      'src/__tests__/categories-unit.test.ts',
      'src/__tests__/orders-pagination-speed.test.ts',
      'src/__tests__/auto-map-poll-category.test.ts',
      'src/__tests__/p0-security-fixes.test.ts',
      'src/__tests__/actionable-error.test.ts',
      'src/__tests__/admin-stress/admin-panel-stress-and-resilience.test.ts',
      'src/__tests__/checkout-payments/checkout-resilience-and-bypass.test.ts',
      'src/__tests__/mobile-wizard-smoke.test.tsx',
      'src/__tests__/admin-nav-active.test.ts',
      'src/lib/__tests__/order-token-and-typo-guard.test.ts',
      'src/__tests__/financial/yookassa-signed-webhook-verification.test.ts',
      'src/__tests__/auth/logout-and-proxy-redirects.test.ts',
      'src/__tests__/auth/user-login-and-logout-resilience.test.ts',
      'src/lib/icons/__tests__/safe-svg.test.ts',
      'src/__tests__/order-actions-and-support-ops.test.ts',
      'src/__tests__/providers/balance-autoflush-resilience.test.ts',
      'src/__tests__/financial/ledger-and-transaction-type-filters.test.ts',
      'src/__tests__/financial/escrow-quarantine-double-entry.test.ts',
      'src/__tests__/catalog/category-slug-and-icon-hygiene.test.ts',
      'src/actions/admin/providers/__tests__/sync-provider-catalog.test.ts',
      'src/__tests__/orders/order-triage-and-autoflush-logic.test.ts',
      'src/__tests__/orders/order-ttl-and-provider-lifecycle-matrix.test.ts',
      'src/workers/processors/__tests__/zero-start-detector.test.ts',
      'src/workers/processors/__tests__/pending-check-resolution.test.ts',
      'src/__tests__/catalog/empty-categories-cleanup.test.ts',
      'src/__tests__/security/optimization-security-and-rbac.test.ts',
      'src/__tests__/security/swarm-optimization-premortem-security.test.ts',
      'src/__tests__/security/pentest-owasp-defense-invariants.test.ts',
      'src/__tests__/security/owasp-qa-deep-adversarial-audit.test.ts',
      'src/__tests__/settings/settings-cluster-navigation.test.ts',
      'src/__tests__/clients/client-ledger-and-notes.test.ts',
      'src/__tests__/support/ai-response-sanitizer.test.ts',
      'src/__tests__/staff/staff-shifts-collisions.test.ts',
      'src/__tests__/finance/manual-payment-approval.test.ts',
      'src/__tests__/security/owasp-2026-comprehensive-adversarial.test.ts',
      'src/__tests__/security/pci-dss-fintech-concurrency-audit.test.ts',
      'src/__tests__/security/ip-parser.test.ts',
      'src/__tests__/security/maintenance-status.test.ts',
      'src/__tests__/security/dev-auto-login-guard.test.ts',
      'src/__tests__/security/notifications-config.test.ts',
      'src/__tests__/security/auth-token-tenant-isolation.test.ts',
      'src/__tests__/security/staff-session-pinning.test.ts',
      'src/__tests__/security/layout-privacy-and-dom.test.ts',
      'src/__tests__/security/admin-tenant-server-session.test.ts',
      'src/__tests__/security/csp-style-nonce.test.ts',
      'src/__tests__/security/jwt-staff-role-exclusion.test.ts',
      'src/__tests__/security/telegram-bot-security-invariants.test.ts',
      'src/__tests__/security/auth-verify-rate-limit-and-tx.test.ts',
      'src/__tests__/financial/wallet-ops-safety-cap.test.ts',
      'src/__tests__/security/security-alert-escaping.test.ts',
      'src/__tests__/security/logout-security-and-blacklist.test.ts',
      'src/__tests__/security/b2b-vault-encryption.test.ts',
      'src/__tests__/security/insecure-secret-startup-guard.test.ts',
      'src/__tests__/dashboard-bugs-fix-verification.test.ts',
      'src/__tests__/telegram-proxy-agent.test.ts',
    ],
  }
});
