import * as dotenv from 'dotenv';
import path from 'path';
import fs from 'fs';

dotenv.config();

const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;

async function queryModel(model: string, systemPrompt: string, userPrompt: string): Promise<string> {
  console.log(`[OpenRouter] Querying ${model}...`);
  const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
      'HTTP-Referer': 'https://smmplan.pro',
      'X-Title': 'OmniSMM GLM-5.2 Audit',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      temperature: 0.1,
      max_tokens: 3000
    })
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`HTTP ${res.status}: ${errText}`);
  }

  const json = await res.json();
  return json.choices?.[0]?.message?.content || '';
}

async function main() {
  console.log('🚀 Executing GLM-5.2 Adversarial Audit on Category Architecture...');

  const categoryActions = fs.readFileSync('src/actions/admin/catalog/categories.ts', 'utf8');
  const categoryPage = fs.readFileSync('src/app/admin/catalog/categories/page.tsx', 'utf8');

  const context = `
PROJECT: OmniSMM 1.0 (Dual-Brand SMM Architecture: smmplan.pro & smmflux.ru)
TASK: Category & Network Management System Audit

CODE:
=== 1. SERVER ACTIONS (src/actions/admin/catalog/categories.ts) ===
${categoryActions}

=== 2. ADMIN CATEGORIES PAGE (src/app/admin/catalog/categories/page.tsx) ===
${categoryPage}
`;

  const prompt = `
Проведи детальный состязательный аудит безопасности и архитектуры управления категориями и соцсетями на платформе OmniSMM 1.0.

Оцени:
1. Безопасность и RBAC (разграничение прав requireStaffPermission('CATALOG', 'edit'), защита от несанкционированного доступа).
2. Защиту данных и транзакций (защита от удаления категорий с активными услугами, логика слияния mergeCategoriesAction, аудит auditAdminAwaitable).
3. Мультитенантность (tenantId: smmplan, flux, all; видимость в каталоге и витринах).
4. Валидацию данных (zod схемы, slug, ограничения длины, теги Link Analyzer, предупреждения для клиентов).
5. Итоговую оценку архитектурной зрелости (1-10) и таблицу рекомендаций.
`;

  const candidateModels = [
    'z-ai/glm-5.2:free',
    'minimax/minimax-m3:free',
    'nvidia/nemotron-3-ultra-550b-a55b:free',
    'openrouter/free'
  ];

  let auditResult = '';
  let modelUsed = '';

  for (const model of candidateModels) {
    try {
      console.log(`Attempting audit with model: ${model}...`);
      auditResult = await queryModel(model, 'Ты — старший архитектор безопасности и ведущий состязательный аудитор.', context + '\n\n' + prompt);
      if (auditResult && auditResult.length > 200) {
        modelUsed = model;
        console.log(`✅ Audit successfully generated by ${model}! (${auditResult.length} chars)`);
        break;
      }
    } catch (err: any) {
      console.warn(`Model ${model} returned error: ${err.message}`);
      await new Promise(r => setTimeout(r, 2000));
    }
  }

  if (!auditResult) {
    throw new Error('Could not get response from any candidate model');
  }

  const finalReport = `# 🛡️ ОТЧЁТ СОСТЯЗАТЕЛЬНОГО АУДИТА: ${modelUsed.toUpperCase()}
**Объект аудита:** Архитектура управления категориями и соцсетями OmniSMM 1.0
**Дата проведения:** ${new Date().toISOString()}

${auditResult}
`;

  fs.writeFileSync('scripts/harness/GLM_CATEGORY_AUDIT_REPORT.md', finalReport, 'utf8');
  console.log('📄 Saved audit report to scripts/harness/GLM_CATEGORY_AUDIT_REPORT.md');
}

main().catch(err => {
  console.error('Audit execution error:', err);
  process.exit(1);
});
