import React from 'react';
import type { FluxNetwork, FluxCategory, FluxService } from '@/types/flux';

export interface FluxDashboardStepCheckoutProps {
  direction: number;
  selectedService: FluxService;
  activeNetwork: FluxNetwork | null;
  activeCategory: FluxCategory | null;
  link: string;
  setLink: (link: string) => void;
  linkRef: React.RefObject<HTMLInputElement | null>;
  quantity: number | string;
  setQuantity: (qty: number | string) => void;
  quantityRef: React.RefObject<HTMLInputElement | null>;
  qtyNum: number;
  isDripFeedEnabled: boolean;
  setIsDripFeedEnabled: (enabled: boolean) => void;
  dripRuns: number;
  setDripRuns: (runs: number) => void;
  dripInterval: number;
  setDripInterval: (interval: number) => void;
  customData: string;
  setCustomData: (data: string) => void;
  customDataRef: React.RefObject<HTMLTextAreaElement | null>;
  isRequirementsConfirmed: boolean;
  setIsRequirementsConfirmed: (confirmed: boolean) => void;
  requirementRef: React.RefObject<HTMLDivElement | null>;
  email: string;
  setEmail: (email: string) => void;
  emailRef: React.RefObject<HTMLInputElement | null>;
  showPromo: boolean;
  setShowPromo: (show: boolean) => void;
  promoCode: string;
  setPromoCode: (code: string) => void;
  appliedPromo: string;
  isApplyingPromo: boolean;
  promoMessage: { type: 'success' | 'error'; text: string } | null;
  handleApplyPromo: () => void;
  handleRemovePromo: () => void;
  gateway: 'balance' | 'yookassa' | 'cryptobot';
  setGateway: (gateway: 'balance' | 'yookassa' | 'cryptobot') => void;
  availableGateways: { yookassa: boolean; robokassa: boolean; cryptobot: boolean };
  userBalanceRub: string;
  canPayFromBalance: boolean;
  totalPriceRub: string;
  originalServerPriceRub: number | null;
  discountPercent: number;
  errorMessage: string | null;
  errorField: string | null;
  shakeKey: number;
  isSubmitting: boolean;
  setIsTgGuideOpen: (open: boolean) => void;
  onSubmit: (e: React.FormEvent) => void;
}
