import type { DlpCheckResult } from '@/types/ai-support';

export class OutputDlpService {
  private static readonly OFFICIAL_DOMAINS = [
    'smmplan.pro',
    'smmflux.ru',
    'desktop-25m6el7.tailbb9d28.ts.net',
  ];

  /**
   * Scans and sanitizes the output generated by Gemini before it is delivered to the client.
   * Prevents leaks of competitor/client channels, API keys, internal prompts, and legal liabilities.
   */
  public static sanitize(rawText: string, brandName: string = 'SMMplan'): DlpCheckResult {
    if (!rawText || typeof rawText !== 'string') {
      return { cleanText: '', blocked: false };
    }

    let text = rawText.trim();

    // 1. Проверка на случайную утечку приватных ссылок на каналы/профили соцсетей
    // Разрешены только официальные домены платформы (smmplan.pro / smmflux.ru)
    const channelLinkRegex = /(?:https?:\/\/)?(?:t\.me|vk\.com|instagram\.com|youtube\.com|tiktok\.com)\/(?!smmplan|smmflux|track|support)[a-zA-Z0-9_+.-]{4,}/gi;
    if (channelLinkRegex.test(text)) {
      return {
        cleanText: `Здравствуйте! Детали по Вашему заказу доступны в Вашем личном кабинете. В целях безопасности полные ссылки на объекты продвижения в чате не публикуются.\n\n—\n*Сформировано ИИ-ассистентом ${brandName}. Для вызова оператора напишите "оператор"*`,
        blocked: true,
        violation: 'DETECTED_TARGET_LINK_LEAK',
      };
    }

    // 2. Проверка на утечку внутренних токенов, API-ключей и UUID провайдеров
    const secretKeyRegex = /\b(?:[a-f0-9]{32,64}|AIzaSy[A-Za-z0-9_-]{30,40}|ey[A-Za-z0-9-_]{25,})\b/gi;
    if (secretKeyRegex.test(text)) {
      return {
        cleanText: `Здравствуйте! Произошла техническая задержка отображения данных. Ваше обращение передано дежурному специалисту для ручной проверки.\n\n—\n*Сформировано ИИ-ассистентом ${brandName}. Для вызова оператора напишите "оператор"*`,
        blocked: true,
        violation: 'DETECTED_API_KEY_OR_TOKEN',
      };
    }

    // 3. Проверка на утечку системного промпта и служебных инструкций
    const promptLeakRegex = /(?:<untrusted_user_input>|executeOrderLookup|ФУНДАМЕНТАЛЬНЫЙ БАРЬЕР|ПРАВИЛО НУЛЕВОГО ДОВЕРИЯ|System Instruction)/i;
    if (promptLeakRegex.test(text)) {
      return {
        cleanText: `Здравствуйте! Чем я могу помочь Вам по Вашим заказам в службе заботы ${brandName}?\n\n—\n*Сформировано ИИ-ассистентом ${brandName}. Для вызова оператора напишите "оператор"*`,
        blocked: true,
        violation: 'DETECTED_SYSTEM_PROMPT_LEAK',
      };
    }

    // 4. Защита от признания юридической вины и незаконных обещаний (ст. 15 38-ФЗ и ГК РФ)
    const liabilityRegex = /(?:признаем вину|мы виноваты|мы нарушили закон|гарантируем 100%|гарантируем отсутствие банов)/i;
    if (liabilityRegex.test(text)) {
      return {
        cleanText: `Здравствуйте! Ваше обращение принято и передано дежурному менеджеру для согласования решения. Мы ответим Вам в ближайшее время.\n\n—\n*Сформировано ИИ-ассистентом ${brandName}. Для вызова оператора напишите "оператор"*`,
        blocked: true,
        violation: 'LEGAL_LIABILITY_ADMISSION',
      };
    }

    // 5. Обязательный AI-дисклеймер в конце ответа (ст. 10 ЗоЗПП)
    const disclaimerSignature = `\n\n—\n*Сформировано ИИ-ассистентом ${brandName}. Для вызова оператора напишите "оператор"*`;
    if (!text.includes('Сформировано ИИ-ассистентом')) {
      text += disclaimerSignature;
    }

    return {
      cleanText: text,
      blocked: false,
    };
  }
}
