import * as fs from 'fs';
import * as path from 'path';

const IGNORE_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  'dist',
  'out',
  '.agent',
  '.gemini'
]);

const ALLOWED_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.json', '.css', '.prisma', '.html', '.env'
]);

interface DebtItem {
  filePath: string;
  line: number;
  type: 'TODO' | 'FIXME' | 'HACK';
  message: string;
}

const DEBT_REGEX = /(?:\/\/|(?:\/\*)|#)\s*(TODO|FIXME|HACK):?\s*(.*)/i;

function scanFileForDebt(filePath: string): DebtItem[] {
  const items: DebtItem[] = [];
  const ext = path.extname(filePath).toLowerCase();
  
  if (!ALLOWED_EXTENSIONS.has(ext)) {
    return items;
  }

  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const match = lines[i].match(DEBT_REGEX);
      if (match) {
        items.push({
          filePath,
          line: i + 1,
          type: match[1].toUpperCase() as 'TODO' | 'FIXME' | 'HACK',
          message: match[2].replace(/\*\/$/, '').trim()
        });
      }
    }
  } catch (err) {}

  return items;
}

function walkDir(dir: string, allDebt: DebtItem[]) {
  let files: string[];
  try {
    files = fs.readdirSync(dir);
  } catch (err) {
    return;
  }

  for (const file of files) {
    const fullPath = path.join(dir, file);
    let stat: fs.Stats;
    try {
      stat = fs.statSync(fullPath);
    } catch (err) {
      continue;
    }

    if (stat.isDirectory()) {
      if (IGNORE_DIRS.has(file)) {
        continue;
      }
      walkDir(fullPath, allDebt);
    } else if (stat.isFile()) {
      const debt = scanFileForDebt(fullPath);
      allDebt.push(...debt);
    }
  }
}

function main() {
  console.log('🔧 Technical Debt Annotator: Scanning codebase for TODO/FIXME/HACK notes...');
  const rootDir = path.resolve(process.cwd());
  
  const allDebt: DebtItem[] = [];
  walkDir(rootDir, allDebt);

  const todos = allDebt.filter(d => d.type === 'TODO');
  const fixmes = allDebt.filter(d => d.type === 'FIXME');
  const hacks = allDebt.filter(d => d.type === 'HACK');

  console.log('\n--- 📊 Technical Debt Index Summary ---');
  console.log(`  Total Debt Items Found: ${allDebt.length}`);
  console.log(`    - TODOs:   ${todos.length}`);
  console.log(`    - FIXMEs:  ${fixmes.length}`);
  console.log(`    - HACKs:   ${hacks.length}`);
  console.log('-'.repeat(80));

  if (allDebt.length === 0) {
    console.log('✅ Clean Slate! No technical debt markers found. Fantastic code health!');
    process.exit(0);
  }

  // Group by file for clean output
  const grouped = allDebt.reduce((acc, item) => {
    if (!acc[item.filePath]) {
      acc[item.filePath] = [];
    }
    acc[item.filePath].push(item);
    return acc;
  }, {} as Record<string, DebtItem[]>);

  console.log('\n--- 📄 Detailed Debt Registry ---');
  for (const [file, items] of Object.entries(grouped)) {
    console.log(`\n📄 File: ${path.relative(rootDir, file)}`);
    items.forEach(item => {
      const icon = item.type === 'FIXME' ? '🚨' : item.type === 'HACK' ? '⚡' : '📝';
      console.log(`  ${icon} Line ${item.line.toString().padStart(3, ' ')} [${item.type}]: ${item.message}`);
    });
  }

  // Proactively generate a persistent markdown report under `.agent/technical_debt_report.md`
  const reportPath = path.join(rootDir, '.agent/technical_debt_report.md');
  const dateStr = new Date().toISOString().split('T')[0];
  let mdContent = `# Technical Debt Audit Report - ${dateStr}\n\n`;
  mdContent += `This is an autogenerated registry of technical debt notes in the Smmplan codebase.\n\n`;
  mdContent += `## Summary Metrics\n`;
  mdContent += `- **Total items**: ${allDebt.length}\n`;
  mdContent += `- **TODOs**: ${todos.length}\n`;
  mdContent += `- **FIXMEs**: ${fixmes.length}\n`;
  mdContent += `- **HACKs**: ${hacks.length}\n\n`;
  mdContent += `## Active Debt Registry\n\n`;

  for (const [file, items] of Object.entries(grouped)) {
    mdContent += `### [${path.basename(file)}](file:///${file.replace(/\\/g, '/')})\n`;
    mdContent += `*Relative Path: \`${path.relative(rootDir, file)}\`*\n\n`;
    mdContent += `| Line | Type | Description |\n`;
    mdContent += `| :---: | :--- | :--- |\n`;
    items.forEach(item => {
      mdContent += `| ${item.line} | **${item.type}** | ${item.message} |\n`;
    });
    mdContent += `\n`;
  }

  try {
    const parentDir = path.dirname(reportPath);
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }
    fs.writeFileSync(reportPath, mdContent, 'utf-8');
    console.log(`\n💾 Saved detailed technical debt report to ${reportPath}`);
  } catch (err: any) {
    console.error(`\n❌ Failed to write report file: ${err.message}`);
  }

  process.exit(0);
}

if (require.main === module) {
  main();
}
